-- MySQL Script generated by MySQL Workbench
-- Thu Oct  6 15:32:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema solarium
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `solarium` ;

-- -----------------------------------------------------
-- Schema solarium
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `solarium` DEFAULT CHARACTER SET utf8 ;
USE `solarium` ;

-- -----------------------------------------------------
-- Table `solarium`.`modell`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`modell` (
  `mod_id` INT NOT NULL AUTO_INCREMENT,
  `mod_name` VARCHAR(45) NULL,
  PRIMARY KEY (`mod_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solarium`.`lager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`lager` (
  `lag_id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`lag_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solarium`.`sonnenbank`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`sonnenbank` (
  `son_id` INT NOT NULL AUTO_INCREMENT,
  `mod_id` INT NOT NULL,
  `son_lag_id` INT NULL,
  `son_datum` DATE NOT NULL,
  PRIMARY KEY (`son_id`),
  INDEX `fk_sonnenbank_modell1_idx` (`mod_id` ASC) VISIBLE,
  INDEX `fk_sonnenbank_lager1_idx` (`son_lag_id` ASC) VISIBLE,
  CONSTRAINT `fk_sonnenbank_modell1`
    FOREIGN KEY (`mod_id`)
    REFERENCES `solarium`.`modell` (`mod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sonnenbank_lager1`
    FOREIGN KEY (`son_lag_id`)
    REFERENCES `solarium`.`lager` (`lag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solarium`.`raum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`raum` (
  `rau_id` INT NOT NULL AUTO_INCREMENT,
  `rau_bez` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rau_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solarium`.`kosten`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`kosten` (
  `kos_id` INT NOT NULL AUTO_INCREMENT,
  `kos_einheit` INT NOT NULL,
  `kos_preis` DOUBLE NOT NULL,
  `kos_mod_id` INT NOT NULL,
  `kos_datum` DATE NOT NULL,
  PRIMARY KEY (`kos_id`),
  INDEX `fk_kosten_modell1_idx` (`kos_mod_id` ASC) VISIBLE,
  CONSTRAINT `fk_kosten_modell1`
    FOREIGN KEY (`kos_mod_id`)
    REFERENCES `solarium`.`modell` (`mod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solarium`.`gutschrift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`gutschrift` (
  `gut_id` INT NOT NULL AUTO_INCREMENT,
  `gut_bez` VARCHAR(32) NOT NULL,
  `gut_preis` INT NOT NULL,
  `gut_menge` INT NULL,
  `gut_datum` DATE NOT NULL,
  PRIMARY KEY (`gut_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solarium`.`kunde`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`kunde` (
  `kun_id` INT NOT NULL AUTO_INCREMENT,
  `kun_vname` VARCHAR(45) NOT NULL,
  `kun_nname` VARCHAR(45) NOT NULL,
  `kun_plz` INT NOT NULL,
  PRIMARY KEY (`kun_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solarium`.`verwendung`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`verwendung` (
  `ver_kun_id` INT NULL,
  `ver_son_id` INT NULL,
  `ver_datetime` DATETIME NULL,
  PRIMARY KEY (`ver_kun_id`, `ver_son_id`),
  INDEX `fk_kunde_has_sonnenbank_sonnenbank1_idx` (`ver_son_id` ASC) VISIBLE,
  INDEX `fk_kunde_has_sonnenbank_kunde1_idx` (`ver_kun_id` ASC) VISIBLE,
  CONSTRAINT `fk_kunde_has_sonnenbank_kunde1`
    FOREIGN KEY (`ver_kun_id`)
    REFERENCES `solarium`.`kunde` (`kun_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kunde_has_sonnenbank_sonnenbank1`
    FOREIGN KEY (`ver_son_id`)
    REFERENCES `solarium`.`sonnenbank` (`son_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solarium`.`kunde_gutschrift`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`kunde_gutschrift` (
  `kugu_kun_id` INT NOT NULL,
  `kugu_gut_id` INT NOT NULL,
  INDEX `fk_kunde_has_gutschrift_gutschrift1_idx` (`kugu_gut_id` ASC) VISIBLE,
  INDEX `fk_kunde_has_gutschrift_kunde1_idx` (`kugu_kun_id` ASC) VISIBLE,
  CONSTRAINT `fk_kunde_has_gutschrift_kunde1`
    FOREIGN KEY (`kugu_kun_id`)
    REFERENCES `solarium`.`kunde` (`kun_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kunde_has_gutschrift_gutschrift1`
    FOREIGN KEY (`kugu_gut_id`)
    REFERENCES `solarium`.`gutschrift` (`gut_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `solarium`.`sonnenbank_raum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `solarium`.`sonnenbank_raum` (
  `sora_son_id` INT NOT NULL,
  `sora_rau_id` INT NOT NULL,
  PRIMARY KEY (`sora_son_id`, `sora_rau_id`),
  INDEX `fk_sonnenbank_has_raum_raum1_idx` (`sora_rau_id` ASC) VISIBLE,
  INDEX `fk_sonnenbank_has_raum_sonnenbank1_idx` (`sora_son_id` ASC) VISIBLE,
  CONSTRAINT `fk_sonnenbank_has_raum_sonnenbank1`
    FOREIGN KEY (`sora_son_id`)
    REFERENCES `solarium`.`sonnenbank` (`son_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sonnenbank_has_raum_raum1`
    FOREIGN KEY (`sora_rau_id`)
    REFERENCES `solarium`.`raum` (`rau_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `solarium`.`modell`
-- -----------------------------------------------------
START TRANSACTION;
USE `solarium`;
INSERT INTO `solarium`.`modell` (`mod_id`, `mod_name`) VALUES (DEFAULT, 'Power800');
INSERT INTO `solarium`.`modell` (`mod_id`, `mod_name`) VALUES (DEFAULT, 'GluckGluck9000');
INSERT INTO `solarium`.`modell` (`mod_id`, `mod_name`) VALUES (DEFAULT, 'Suuuiii69420');

COMMIT;


-- -----------------------------------------------------
-- Data for table `solarium`.`sonnenbank`
-- -----------------------------------------------------
START TRANSACTION;
USE `solarium`;
INSERT INTO `solarium`.`sonnenbank` (`son_id`, `mod_id`, `son_lag_id`, `son_datum`) VALUES (DEFAULT, 1, NULL, '2021-03-02');
INSERT INTO `solarium`.`sonnenbank` (`son_id`, `mod_id`, `son_lag_id`, `son_datum`) VALUES (DEFAULT, 2, NULL, '2018-07-04');
INSERT INTO `solarium`.`sonnenbank` (`son_id`, `mod_id`, `son_lag_id`, `son_datum`) VALUES (DEFAULT, 3, NULL, '2021-12-12');
INSERT INTO `solarium`.`sonnenbank` (`son_id`, `mod_id`, `son_lag_id`, `son_datum`) VALUES (DEFAULT, 3, NULL, '2001-09-11');

COMMIT;


-- -----------------------------------------------------
-- Data for table `solarium`.`raum`
-- -----------------------------------------------------
START TRANSACTION;
USE `solarium`;
INSERT INTO `solarium`.`raum` (`rau_id`, `rau_bez`) VALUES (DEFAULT, 'Miami');
INSERT INTO `solarium`.`raum` (`rau_id`, `rau_bez`) VALUES (DEFAULT, 'Sibirien');
INSERT INTO `solarium`.`raum` (`rau_id`, `rau_bez`) VALUES (DEFAULT, 'Ukraine');

COMMIT;


-- -----------------------------------------------------
-- Data for table `solarium`.`sonnenbank_raum`
-- -----------------------------------------------------
START TRANSACTION;
USE `solarium`;
INSERT INTO `solarium`.`sonnenbank_raum` (`sora_son_id`, `sora_rau_id`) VALUES (1,1);
INSERT INTO `solarium`.`sonnenbank_raum` (`sora_son_id`, `sora_rau_id`) VALUES (2,2);
INSERT INTO `solarium`.`sonnenbank_raum` (`sora_son_id`, `sora_rau_id`) VALUES (3,3);

COMMIT;


-- -----------------------------------------------------
-- Data for table `solarium`.`kosten`
-- -----------------------------------------------------
START TRANSACTION;
USE `solarium`;
INSERT INTO `solarium`.`kosten` (`kos_id`, `kos_einheit`, `kos_preis`, `kos_mod_id`, `kos_datum`) VALUES (DEFAULT, 1, 3, 1, '2021-06-12');
INSERT INTO `solarium`.`kosten` (`kos_id`, `kos_einheit`, `kos_preis`, `kos_mod_id`, `kos_datum`) VALUES (DEFAULT, 1, 12, 2, '2001-09-11');
INSERT INTO `solarium`.`kosten` (`kos_id`, `kos_einheit`, `kos_preis`, `kos_mod_id`, `kos_datum`) VALUES (DEFAULT, 1, 7, 3, '2021-12-24');

COMMIT;


-- -----------------------------------------------------
-- Data for table `solarium`.`gutschrift`
-- -----------------------------------------------------
START TRANSACTION;
USE `solarium`;
INSERT INTO `solarium`.`gutschrift` (`gut_id`, `gut_bez`, `gut_preis`, `gut_menge`, `gut_datum`) VALUES (DEFAULT, "Mega", 135, 150, '2021-02-03');
INSERT INTO `solarium`.`gutschrift` (`gut_id`, `gut_bez`, `gut_preis`, `gut_menge`, `gut_datum`) VALUES (DEFAULT, "Ultra", 200, 203, '2021-05-28');
INSERT INTO `solarium`.`gutschrift` (`gut_id`, `gut_bez`, `gut_preis`, `gut_menge`, `gut_datum`) VALUES (DEFAULT, "Omega", 300, 350, '2021-12-10');

COMMIT;


-- -----------------------------------------------------
-- Data for table `solarium`.`kunde`
-- -----------------------------------------------------
START TRANSACTION;
USE `solarium`;
INSERT INTO `solarium`.`kunde` (`kun_id`, `kun_vname`, `kun_nname`, `kun_plz`) VALUES (DEFAULT, 'Kurt', 'Bauer', 4676);
INSERT INTO `solarium`.`kunde` (`kun_id`, `kun_vname`, `kun_nname`, `kun_plz`) VALUES (DEFAULT, 'Georg', 'Maier', 1234);
INSERT INTO `solarium`.`kunde` (`kun_id`, `kun_vname`, `kun_nname`, `kun_plz`) VALUES (DEFAULT, 'Gertrude', 'Nass', 4020);

COMMIT;


-- -----------------------------------------------------
-- Data for table `solarium`.`kunde_gutschrift`
-- -----------------------------------------------------
START TRANSACTION;
USE `solarium`;
INSERT INTO `solarium`.`kunde_gutschrift` (`kugu_kun_id`, `kugu_gut_id`) VALUES (1,1);
INSERT INTO `solarium`.`kunde_gutschrift` (`kugu_kun_id`, `kugu_gut_id`) VALUES (2,2);
INSERT INTO `solarium`.`kunde_gutschrift` (`kugu_kun_id`, `kugu_gut_id`) VALUES (3,3);
INSERT INTO `solarium`.`kunde_gutschrift` (`kugu_kun_id`, `kugu_gut_id`) VALUES (1,2);
INSERT INTO `solarium`.`kunde_gutschrift` (`kugu_kun_id`, `kugu_gut_id`) VALUES (2,3);

COMMIT;

-- -----------------------------------------------------
-- Data for table `solarium`.`verwendung`
-- -----------------------------------------------------
START TRANSACTION;
USE `solarium`;
INSERT INTO `solarium`.`verwendung` (`ver_kun_id`, `ver_son_id`, `ver_datetime`) VALUES (1, 1, '2021-12-02');
INSERT INTO `solarium`.`verwendung` (`ver_kun_id`, `ver_son_id`, `ver_datetime`) VALUES (2, 2, '2021-07-22');
INSERT INTO `solarium`.`verwendung` (`ver_kun_id`, `ver_son_id`, `ver_datetime`) VALUES (3, 3, '2021-10-28');

COMMIT;

USE `solarium`;

-- a)
select	distinct mod_name as "Modell",
		count(son_id) as "Anzahl"
from	modell natural join sonnenbank
group by mod_name;

-- b)
INSERT INTO `solarium`.`modell` (`mod_id`, `mod_name`) VALUES (DEFAULT, 'Susomat420');
INSERT INTO `solarium`.`modell` (`mod_id`, `mod_name`) VALUES (DEFAULT, 'Pogerator2');

-- c)
INSERT INTO `solarium`.`sonnenbank` (`son_id`, `mod_id`, `son_lag_id`, `son_datum`) VALUES 
(DEFAULT, 5, NULL, '2004-11-14'),
(DEFAULT, 4, NULL, '2005-02-23'),
(DEFAULT, 3, NULL, '2015-03-03');

-- d)
select	distinct mod_name as "Modell",
		count(son_id) as "Anzahl"
from	modell natural join sonnenbank
group by mod_name
having count(son_id) > 2;

-- e)
select	count(kugu_kun_id) as "Anzahl der verkauften Gutscheine"
from	kunde_gutschrift;

-- f)
select	r.rau_bez as "Kabine",
		s.son_id as "SonnenbankID",
        m.mod_name as "Modell",
        s.son_datum as "Datum"
from	sonnenbank_raum sr, raum r, sonnenbank s, modell m
where	sr.sora_rau_id = r.rau_id
and		sr.sora_son_id = s.son_id
and		s.mod_id = m.mod_id;

-- g)
select	distinct concat(k.kun_vname, ' ', k.kun_nname) as "Kunde",
		count(g.gut_id) as "Anzahl Gutscheine"
from	kunde_gutschrift kg, kunde k, gutschrift g
where	kg.kugu_kun_id = k.kun_id
and		kg.kugu_gut_id = g.gut_id
group by concat(k.kun_vname, ' ', k.kun_nname);

-- f)
select	gut_bez "Gutscheinbezeichnung",
		gut_preis "Preis",
        gut_menge "Wert",
        (gut_menge-gut_preis) "Wertdifferenz"
from	gutschrift
order by gut_datum;
